<<<<<<< HEAD
---
title: "TSA_FinalProject_Coding"
output: html_document
date: "2023-03-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## install packages

```{r package, message=FALSE, include=FALSE}
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(kableExtra)
library(knitr)

```

## Dataset Information

```{r}
#Import the excel file
library(readxl)
electricity_consumption <- read_excel(path="./Table_2.1a__Energy_Consumption__Residential_-_Commercial_-_and_Industrial_Sectors.xlsx",skip = 10, sheet="Monthly Data",col_names=TRUE) 

#delete the first row with units
electricity_consumption<-electricity_consumption[-1,]

#Keep two columns: primary energy consumption and energy losses for three sectors, respectively
electricity_consumption<-electricity_consumption[,-3][,-3][,-4]
electricity_consumption<-electricity_consumption[,-5][,-5][,-6]
electricity_consumption<-electricity_consumption[,-7][,-7][,-8]

#Round to three digits for all columns
class(electricity_consumption$`Primary Energy Consumed by the Residential Sector`)
electricity_consumption$`Primary Energy Consumed by the Residential Sector` <- as.numeric(electricity_consumption$`Primary Energy Consumed by the Residential Sector`)
round(electricity_consumption$`Primary Energy Consumed by the Residential Sector`,digits=3)

class(electricity_consumption$`Residential Sector Electrical System Energy Losses`)
electricity_consumption$`Residential Sector Electrical System Energy Losses` <- as.numeric(electricity_consumption$`Residential Sector Electrical System Energy Losses`)
round(electricity_consumption$`Residential Sector Electrical System Energy Losses`,digits=3)

class(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`)
electricity_consumption$`Primary Energy Consumed by the Commercial Sector` <- as.numeric(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`)
round(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`,digits=3)

class(electricity_consumption$`Commercial Sector Electrical System Energy Losses`)
electricity_consumption$`Commercial Sector Electrical System Energy Losses` <- as.numeric(electricity_consumption$`Commercial Sector Electrical System Energy Losses`)
round(electricity_consumption$`Commercial Sector Electrical System Energy Losses`,digits=3)

class(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`)
electricity_consumption$`Primary Energy Consumed by the Industrial Sector` <- as.numeric(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`)
round(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`,digits=3)

class(electricity_consumption$`Industrial Sector Electrical System Energy Losses`)
electricity_consumption$`Industrial Sector Electrical System Energy Losses` <- as.numeric(electricity_consumption$`Industrial Sector Electrical System Energy Losses`)
round(electricity_consumption$`Industrial Sector Electrical System Energy Losses`,digits=3)

head(electricity_consumption)
```

```{r}
#Transform to time series data
Date_frame<-as.Date(electricity_consumption$Month)
ts_electricity <- ts(electricity_consumption[,2:7],start=c(1973,01),end=c(2022,11),frequency=12)

#Summary of time series data
summary_data<-summary(ts_electricity)
summary_data

#Calculate means, standard deviations, and ranges for each variable

mean_R1<-mean(electricity_consumption$`Primary Energy Consumed by the Residential Sector`)
sd_R1<-sd(electricity_consumption$`Primary Energy Consumed by the Residential Sector`)
range_R1<-max(electricity_consumption$`Primary Energy Consumed by the Residential Sector`)-min(electricity_consumption$`Primary Energy Consumed by the Residential Sector`)

mean_R2<-mean(electricity_consumption$`Residential Sector Electrical System Energy Losses`)
sd_R2<-sd(electricity_consumption$`Residential Sector Electrical System Energy Losses`)
range_R2<-max(electricity_consumption$`Residential Sector Electrical System Energy Losses`)-min(electricity_consumption$`Residential Sector Electrical System Energy Losses`)

mean_C1<-mean(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`)
sd_C1<-sd(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`)
range_C1<-max(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`)-min(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`)

mean_C2<-mean(electricity_consumption$`Commercial Sector Electrical System Energy Losses`)
sd_C2<-sd(electricity_consumption$`Commercial Sector Electrical System Energy Losses`)
range_C2<-max(electricity_consumption$`Commercial Sector Electrical System Energy Losses`)-min(electricity_consumption$`Commercial Sector Electrical System Energy Losses`)

mean_I1<-mean(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`)
sd_I1<-sd(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`)
range_I1<-max(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`)-min(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`)

mean_I2<-mean(electricity_consumption$`Industrial Sector Electrical System Energy Losses`)
sd_I2<-sd(electricity_consumption$`Industrial Sector Electrical System Energy Losses`)
range_I2<-max(electricity_consumption$`Industrial Sector Electrical System Energy Losses`)-min(electricity_consumption$`Industrial Sector Electrical System Energy Losses`)

# Create a table
summary_df <- data.frame(
  Variable = c("Residential_Sector_Consumption", "Residential_Sector_Losses", "Commercial_Sector_Consumption", "Commercial_Sector_Losses", "Industrial_Sector_Consumption", "Industrial_Sector_Losses"),
  Mean = c(584.60,662.45,345.14,605.47,1806.54,576.51),
  StandardDeviation = c(321.54,185.03,146.90,178.14,146.71,68.86),
  Range = c(1295.71,819.46,538.31,723.97,800.93,371.76)
)
  
summary_table<-kbl(summary_df, caption="Summary Statistics Table used with ts() function") %>% 
  kable_styling(full_width = FALSE, position = "center",latex_options = "hold_position")

summary_table
```



=======
---
title: "TSA_FinalProject_Coding"
output: html_document
date: "2023-03-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## install packages

```{r package, message=FALSE, include=FALSE}
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(kableExtra)
library(knitr)

```

## Dataset Information

```{r}
#Import the excel file
library(readxl)
electricity_consumption <- read_excel(path="./Table_2.1a__Energy_Consumption__Residential_-_Commercial_-_and_Industrial_Sectors.xlsx",skip = 10, sheet="Monthly Data",col_names=TRUE) 

#delete the first row with units
electricity_consumption<-electricity_consumption[-1,]

#Keep two columns: primary energy consumption and energy losses for three sectors, respectively
electricity_consumption<-electricity_consumption[,-3][,-3][,-4]
electricity_consumption<-electricity_consumption[,-5][,-5][,-6]
electricity_consumption<-electricity_consumption[,-7][,-7][,-8]

#Round to three digits for all columns
class(electricity_consumption$`Primary Energy Consumed by the Residential Sector`)
electricity_consumption$`Primary Energy Consumed by the Residential Sector` <- as.numeric(electricity_consumption$`Primary Energy Consumed by the Residential Sector`)
round(electricity_consumption$`Primary Energy Consumed by the Residential Sector`,digits=3)

class(electricity_consumption$`Residential Sector Electrical System Energy Losses`)
electricity_consumption$`Residential Sector Electrical System Energy Losses` <- as.numeric(electricity_consumption$`Residential Sector Electrical System Energy Losses`)
round(electricity_consumption$`Residential Sector Electrical System Energy Losses`,digits=3)

class(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`)
electricity_consumption$`Primary Energy Consumed by the Commercial Sector` <- as.numeric(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`)
round(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`,digits=3)

class(electricity_consumption$`Commercial Sector Electrical System Energy Losses`)
electricity_consumption$`Commercial Sector Electrical System Energy Losses` <- as.numeric(electricity_consumption$`Commercial Sector Electrical System Energy Losses`)
round(electricity_consumption$`Commercial Sector Electrical System Energy Losses`,digits=3)

class(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`)
electricity_consumption$`Primary Energy Consumed by the Industrial Sector` <- as.numeric(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`)
round(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`,digits=3)

class(electricity_consumption$`Industrial Sector Electrical System Energy Losses`)
electricity_consumption$`Industrial Sector Electrical System Energy Losses` <- as.numeric(electricity_consumption$`Industrial Sector Electrical System Energy Losses`)
round(electricity_consumption$`Industrial Sector Electrical System Energy Losses`,digits=3)

colnames(electricity_consumption)<-c('Date','Residential.Primary.Energy','Residential.Energy.Losses','Commercial.Primary.Energy','Commercial.Energy.Losses','Industrial.Primary.Energy','Industrial.Energy.Losses')

head(electricity_consumption)
```

```{r}
#Transform to time series data
Date_frame<-as.Date(electricity_consumption$Month)
ts_electricity <- ts(electricity_consumption[,2:7],start=c(1973,01),end=c(2022,11),frequency=12)

#Summary of time series data
summary_data<-summary(ts_electricity)
summary_data

#Calculate means, standard deviations, and ranges for each variable

mean_R1<-mean(electricity_consumption$`Primary Energy Consumed by the Residential Sector`)
sd_R1<-sd(electricity_consumption$`Primary Energy Consumed by the Residential Sector`)
range_R1<-max(electricity_consumption$`Primary Energy Consumed by the Residential Sector`)-min(electricity_consumption$`Primary Energy Consumed by the Residential Sector`)

mean_R2<-mean(electricity_consumption$`Residential Sector Electrical System Energy Losses`)
sd_R2<-sd(electricity_consumption$`Residential Sector Electrical System Energy Losses`)
range_R2<-max(electricity_consumption$`Residential Sector Electrical System Energy Losses`)-min(electricity_consumption$`Residential Sector Electrical System Energy Losses`)

mean_C1<-mean(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`)
sd_C1<-sd(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`)
range_C1<-max(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`)-min(electricity_consumption$`Primary Energy Consumed by the Commercial Sector`)

mean_C2<-mean(electricity_consumption$`Commercial Sector Electrical System Energy Losses`)
sd_C2<-sd(electricity_consumption$`Commercial Sector Electrical System Energy Losses`)
range_C2<-max(electricity_consumption$`Commercial Sector Electrical System Energy Losses`)-min(electricity_consumption$`Commercial Sector Electrical System Energy Losses`)

mean_I1<-mean(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`)
sd_I1<-sd(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`)
range_I1<-max(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`)-min(electricity_consumption$`Primary Energy Consumed by the Industrial Sector`)

mean_I2<-mean(electricity_consumption$`Industrial Sector Electrical System Energy Losses`)
sd_I2<-sd(electricity_consumption$`Industrial Sector Electrical System Energy Losses`)
range_I2<-max(electricity_consumption$`Industrial Sector Electrical System Energy Losses`)-min(electricity_consumption$`Industrial Sector Electrical System Energy Losses`)

# Create a table
summary_df <- data.frame(
  Variable = c("Residential_Sector_Consumption", "Residential_Sector_Losses", "Commercial_Sector_Consumption", "Commercial_Sector_Losses", "Industrial_Sector_Consumption", "Industrial_Sector_Losses"),
  Mean = c(584.60,662.45,345.14,605.47,1806.54,576.51),
  StandardDeviation = c(321.54,185.03,146.90,178.14,146.71,68.86),
  Range = c(1295.71,819.46,538.31,723.97,800.93,371.76)
)
  
summary_table<-kbl(summary_df, caption="Summary Statistics Table used with ts() function") %>% 
  kable_styling(full_width = FALSE, position = "center",latex_options = "hold_position")

summary_table
```


## Initial Plots

```{r}
#plot for electricity consumption
cols<-c("residential"="orange","commercial"="steelblue","industrial"="yellow")
ts_plot<-ggplot(electricity_consumption)+
  geom_line(aes(x=Date,y=Residential.Primary.Energy,color="residential"))+
  ylab(paste0("Electricity Consumption (Trillion BTU)",sep="")) +
  xlab("Date")+
  geom_line(aes(x=Date,y=Commercial.Primary.Energy,color="commercial"))+
  geom_line(aes(x=Date,y=Industrial.Primary.Energy,color="industrial"))+
  labs(title="Primary Electricity Consumption of Three Sectors")+
  scale_color_manual(name="series",values = cols)
plot(ts_plot)
          
#plot for energy losses
cols1<-c("residential"="green","commercial"="red","industrial"="blue")
ts_plot1<-ggplot(electricity_consumption)+
  geom_line(aes(x=Date,y=Residential.Energy.Losses,color="residential"))+
  ylab(paste0("Energy Losses (Trillion BTU)",sep="")) +
  xlab("Date")+
  geom_line(aes(x=Date,y=Commercial.Energy.Losses,color="commercial"))+
  geom_line(aes(x=Date,y=Industrial.Energy.Losses,color="industrial"))+
  labs(title="Energy Losses of Three Sectors")+
  scale_color_manual(name="series",values = cols1)
plot(ts_plot1)

```

###Residential Sector
```{r}
#Create a dataframe only for Residential
electricity_consumption_R<-electricity_consumption[,-4:-7]
colnames(electricity_consumption_R)<-c('Date','Primary.Energy','Energy.Losses')

#Inspect data
#head(electricity_price)
nvar <- ncol(electricity_consumption_R) - 1
nobs <- nrow(electricity_consumption_R)
#transform 
ts_electricity_R <- ts(
  electricity_consumption_R[,2:(nvar+1)],
  start=c(1973,01,10),end=c(2022,11,01),
  frequency=12)

```

##ACF and PACF Plots
```{r}
#ACF and PACF plots
par(mfrow=c(1,4))
ACF_Plot <- Acf(electricity_consumption_R$Primary.Energy, lag = 40, plot = TRUE,main="ACF of Residential Sector Consumption")
PACF_Plot <- Pacf(electricity_consumption_R$Primary.Energy, lag = 40, plot = TRUE,main="PACF of Residential Sector Consumption")
ACF_Plot <- Acf(electricity_consumption_R$Energy.Losses, lag = 40, plot = TRUE,main="ACF of Residential Sector Losses")
PACF_Plot <- Pacf(electricity_consumption_R$Energy.Losses, lag = 40, plot = TRUE,main="PACF of Residential Sector Losses")
```


>>>>>>> 27feebc85033fc781a4571c53e37efd7119918e4

```{r}
#Industrial sector

I_electricity_consumption<-electricity_consumption[c(1,6,7)]
colnames(electricity_consumption_R)<-c('Date','Industrial.Primary.Energy','Energy.Losses')

#Inspect data
#head(electricity_price)
nvar <- ncol(I_electricity_consumption) - 1
nobs <- nrow(I_electricity_consumption)
#transform 
I_ts_electricity <- ts(
  I_electricity_consumption[,2:(nvar+1)],
  start=c(1973,01,10),end=c(2022,11,01),
  frequency=12)
```

```{r}
#Plot ACF and PACF for industrial energy consumption
par(mfrow=c(1,2))
ACF_I_consumption <- Acf(I_electricity_consumption$Industrial.Primary.Energy, lag = 40, plot = TRUE,main="ACF of Industrial Sector Consumption")
PACF_I_consumption <- Pacf(I_electricity_consumption$Industrial.Primary.Energy, lag = 40, plot = TRUE,main="PACF of Industrial Sector Consumption")
#Plot ACF and PACF for industrial energy loss
par(mfrow=c(1,2))
ACF_I_loss <- Acf(I_electricity_consumption$Industrial.Energy.Losses, lag = 40, plot = TRUE,main="ACF of Industrial Sector Losses")
PACF_I_loss <- Pacf(I_electricity_consumption$Industrial.Energy.Losses, lag = 40, plot = TRUE,main="PACF of Industrial Sector Losses")
```

